# Generated by Django 5.2.17 on 2026-08-11 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RDSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly display name', max_length=100)),
                ('db_identifier', models.CharField(help_text='RDS DBInstanceIdentifier', max_length=255)),
                ('region', models.CharField(default='us-east-1', max_length=32)),
                ('host', models.CharField(help_text='RDS endpoint address', max_length=255)),
                ('port', models.PositiveIntegerField(default=5432)),
                ('db_name', models.CharField(max_length=255)),
                ('username', models.CharField(help_text='DB login username', max_length=255)),
                ('password_encrypted', models.CharField(help_text='Fernet-encrypted DB login password', max_length=512)),
                ('ssl_required', models.BooleanField(default=True, help_text='Uncheck for local/dev Postgres without SSL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('kill_session', 'Kill session'), ('add_instance', 'Add instance'), ('remove_instance', 'Remove instance')], max_length=32)),
                ('target_pid', models.IntegerField(blank=True, null=True)),
                ('target_query', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('detail', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='monitor.rdsinstance')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
