# Generated by Django 5.2.17 on 2026-08-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('kill_session', 'Kill session'), ('kill_chain', 'Kill blocking chain'), ('add_instance', 'Add instance'), ('remove_instance', 'Remove instance'), ('rename_instance', 'Rename instance')], max_length=32),
        ),
    ]
