# Generated by Django 5.2.17 on 2026-08-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('kill_session', 'Kill session'), ('kill_chain', 'Kill blocking chain'), ('bulk_kill', 'Bulk kill selected'), ('kill_replication_slot', 'Kill replication slot backend'), ('drop_replication_slot', 'Drop replication slot'), ('add_instance', 'Add instance'), ('remove_instance', 'Remove instance'), ('rename_instance', 'Rename instance')], max_length=32),
        ),
    ]
