# Generated by Django 5.2 on 2026-09-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0019_lock_clear_attribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMFA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secret_encrypted", models.CharField(blank=True, max_length=512)),
                ("backup_codes", models.JSONField(default=list)),
                ("pending_backup_codes_encrypted", models.CharField(blank=True, max_length=2048)),
                ("enabled", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User MFA",
                "verbose_name_plural": "User MFA",
            },
        ),
    ]
