# Generated by Django 5.2 on 2026-09-11

from datetime import time

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0020_usermfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="notification_schedule_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Only send lock notifications during the configured IST window",
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="notification_start_time",
            field=models.TimeField(default=time(9, 0)),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="notification_end_time",
            field=models.TimeField(default=time(21, 0)),
        ),
    ]
