# Generated by Django 5.2 on 2026-09-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0021_notification_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="manual_query_alert_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Alert when non-excluded users run active queries beyond the threshold",
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="manual_query_threshold_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="manual_query_excluded_users",
            field=models.TextField(
                default="applms,applos",
                help_text="Comma-separated database usernames excluded from long-query alerts",
            ),
        ),
        migrations.CreateModel(
            name="LongQueryAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alert_key", models.CharField(max_length=255)),
                ("pid", models.IntegerField()),
                ("username", models.CharField(blank=True, max_length=255)),
                ("application_name", models.CharField(blank=True, max_length=255)),
                ("client_addr", models.CharField(blank=True, max_length=255)),
                ("query", models.TextField(blank=True)),
                ("query_start", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("alerted_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="long_query_alerts",
                        to="monitor.rdsinstance",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="longqueryalert",
            index=models.Index(fields=["instance", "resolved_at"], name="monitor_lon_instanc_1d4b17_idx"),
        ),
        migrations.AddIndex(
            model_name="longqueryalert",
            index=models.Index(fields=["alert_key"], name="monitor_lon_alert_k_7c95a4_idx"),
        ),
        migrations.AddConstraint(
            model_name="longqueryalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resolved_at__isnull", True)),
                fields=("instance", "alert_key"),
                name="unique_active_long_query_alert",
            ),
        ),
    ]
