# Generated by Django 5.2 on 2026-09-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0022_long_query_alerts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="longqueryalert",
            old_name="monitor_lon_instanc_1d4b17_idx",
            new_name="monitor_lon_instanc_1f191b_idx",
        ),
        migrations.RenameIndex(
            model_name="longqueryalert",
            old_name="monitor_lon_alert_k_7c95a4_idx",
            new_name="monitor_lon_alert_k_8f6dcb_idx",
        ),
    ]
