# Generated by Django 5.2.17 on 2026-09-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0039_group_legacy_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdsinstance',
            name='engine',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('mssql', 'MSSQL')], default='postgresql', max_length=16),
        ),
    ]
